### ISSUE TITLE
Documentar a atualização do metaphone-ptbr

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/metaphone-ptbr#7]
Documentar a atualização do metaphone-ptbr

**Comment by crebollobr** [comment]
https://github.com/AddressForAll/metaphone-ptbr/issues/6

**Comment by ppKrauss** [comment]
Depois do _commit_ https://github.com/AddressForAll/metaphone-ptbr/commit/81739af3b887db44c2725b9c26e6a693e0fc920f faltou incluir o `ln -s 9.4 16.1` . Falta também corrigir o link "all -> 9.5" precisa ser "all -> 9.4" para consistência lógica. 

Faltou documentarmos o que teve de mudança entre versões PostgreSQL. 
Ideal agora é gerenciar [releases](https://github.com/AddressForAll/metaphone-ptbr/releases).. Ou contribuir direto na origem do fork, git do Jordão.

Cuidado que depois do `sudo make install` (e avisar nos docs que sem sudo não funciona)  alguns arquivos são gerados mas não precisam ir para o git, 
```
	9.4/metaphoneptbr.bc
	9.4/metaphoneptbr.o
	9.4/metaphoneptbr.so
```

**Comment by crebollobr** [comment]
https://github.com/AddressForAll/metaphone-ptbr/blob/master/release
